name: "units-test"
on:
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ secrets.DOMAIN }}
      TOKEN_DEV_DIR1: ${{ secrets.TOKEN_DEV_DIR1 }}
      TOKEN_DEV_DIR2: ${{ secrets.TOKEN_DEV_DIR2 }}
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ secrets.DOMAIN }}
      TOKEN_DEV_DIR1: ${{ secrets.TOKEN_DEV_DIR1 }}
      TOKEN_DEV_DIR2: ${{ secrets.TOKEN_DEV_DIR2 }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./
